### ISSUE TITLE
[1.20.1] Error generating a Chunk with Garden of Glass

### ISSUE THREAD

**Issue by BOLTMAGIC** [McJty/LostCities#726]
Hey,

Im making a modpack and got a error so I made a new instance with just some mods and tested it again. Got the same error.

https://pastebin.com/FS1ZjFrY

<img width="1920" height="1009" alt="Image" src="https://github.com/user-attachments/assets/246b15d1-0c1e-4742-b08c-50966ef08221" />
<img width="1920" height="1009" alt="Image" src="https://github.com/user-attachments/assets/49527769-b385-45ea-bbf1-df898a790a9b" />
<img width="1920" height="1009" alt="Image" src="https://github.com/user-attachments/assets/10559bea-5ed4-4269-ba6c-f4c35a7a4773" />
<img width="1920" height="1009" alt="Image" src="https://github.com/user-attachments/assets/1d03f4a0-ca2c-4894-8ef9-e55d448b79b8" />
<img width="1920" height="1009" alt="Image" src="https://github.com/user-attachments/assets/f424bf1a-0e60-4e7c-b0c5-746f3dda3758" />
<img width="1920" height="1009" alt="Image" src="https://github.com/user-attachments/assets/5465a17b-e9e7-4e69-8f17-a17225f3d041" />

Im using:
Forge 47.4.6
Lost Cities 1.20 7.4.1
JEI 15.20.0.112
JADE 11.13.2
EMI 1.1.22
Botania Garden of Glass 1.13
Botania 449
Architectury 9.2.14
Curios API 5.14.1
Patchouli 84.1
FTB Library 2001.2.10
FTB Essentials 2001.2.3

Please tell me if you need more infos and have a nice day! 😄

**Comment by BOLTMAGIC** [comment]
Im using default config for lost cities and you can ignore the first 300 lines of the pastbin.

**Comment by BOLTMAGIC** [comment]
I tried it some more and can say its garden of glass. If you spawn in the world type garden of glass and build the lost cities portal (2 diamond blocks, 6 skulls and a bed) you get a lot of errors because the min world height is 0 and not -60. 

Mods used:
Lost Cities 7.4.1
Botania 1.20.1 449 Forge 
Botania Garden of Glass 1.13 (Requirement for Garden of Glass)
Curios API 5.14.1 (Requirement for Botania)
Patchouli 84.1 (Requirement for Botania)

<img width="892" height="522" alt="Image" src="https://github.com/user-attachments/assets/e363ac10-b2fa-4840-9017-776f5ef55726" />

**Comment by BOLTMAGIC** [comment]
[latest.log](https://github.com/user-attachments/files/21678281/latest.log)

**Comment by BOLTMAGIC** [comment]
I fixed it by creating a datapack (just for kubejs) and setting the min y to -64

[data.zip](https://github.com/user-attachments/files/21678820/data.zip)

**Comment by McJty** [comment]
This is now fixed

**Comment by BOLTMAGIC** [comment]
Instance with 350 mods:
https://pastebin.com/T51nPxkk

Instance with 8 mods:
https://pastebin.com/0XzVHWPV



still not fixed.

**Comment by McJty** [comment]
@BOLTMAGIC what version of Lost Cities?

**Comment by BOLTMAGIC** [comment]
Im using lostcities-1.20-7.4.3.jar. and the bug is still there

**Comment by McJty** [comment]
yes I'm checking it now. It's actually a different bug which happens to manifest the same way. Anyway, what type of dimension is that? What are the minimum and maximum heights?

**Comment by BOLTMAGIC** [comment]
its the garden of glass dimension. min height is -85 and max height is 300 (at least)
and creating a portal from the GoG dimension to the lost cities and finding a city will trow a lot of error I linked above

**Comment by McJty** [comment]
Can you give the exact dimensions? Min and max height have to be a multiple of 16 so those values aren't valid

**Comment by BOLTMAGIC** [comment]
gardenofglass:gardenofglass
max height limit 320
min height is -64

**Comment by McJty** [comment]
Thanks. I'll check this out

**Comment by ocrepalde** [comment]
Alguma Atualização?
